development:
  adapter: async

test:
  adapter: test

staging:
  adapter: postgresql

production:
  adapter: postgresql # redis
  # all other options below are only used for redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: code_ocean_production
